# Generated by Django 5.1.3 on 2024-11-30 17:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MartialArt',
            fields=[
                ('martial_art_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='arts_pics/default.png', upload_to='arts_pics')),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('movement_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('martial_art_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='feedback.martialart')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('session_date', models.DateTimeField(auto_now_add=True)),
                ('movement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='feedback.movement')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('progress_score', models.FloatField(validators=[django.core.validators.MaxValueValidator(99.99)])),
                ('movement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_history', to='feedback.movement')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='feedback.practicesession')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
