# Generated by Django 5.1.3 on 2024-11-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresshistory',
            name='progress_score',
        ),
        migrations.RemoveField(
            model_name='progresshistory',
            name='session_id',
        ),
        migrations.AddField(
            model_name='progresshistory',
            name='progress_scores',
            field=models.JSONField(default=list),
        ),
    ]
